#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : offlineimap
Version  : 7.1.4
Release  : 10
URL      : https://github.com/OfflineIMAP/offlineimap/archive/v7.1.4.tar.gz
Source0  : https://github.com/OfflineIMAP/offlineimap/archive/v7.1.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: offlineimap-bin
Requires: offlineimap-python3
Requires: offlineimap-python
Requires: six-legacypython
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
Documentation for the OfflineImap Test suite.
How to run the tests
====================

%package bin
Summary: bin components for the offlineimap package.
Group: Binaries

%description bin
bin components for the offlineimap package.


%package python
Summary: python components for the offlineimap package.
Group: Default
Requires: offlineimap-python3

%description python
python components for the offlineimap package.


%package python3
Summary: python3 components for the offlineimap package.
Group: Default
Requires: python3-core

%description python3
python3 components for the offlineimap package.


%prep
%setup -q -n offlineimap-7.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523307972
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/offlineimap

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
